#!/bin/sh

echo "Switching to branch main"
git checkout main

echo "Building app"
cd frontend
npm run build

echo "Deploying build files to server"
rsync -avP build/ luke@lukew3.com:/home/luke/buildmyidea/build/
echo "Git pulling on server"
ssh luke@lukew3.com << DONE
cd ~/buildmyidea
git pull
cd ..
sudo ./notes
DONE
echo "Deployment complete"
